<?php

namespace Minsal\shcpBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ShcpParCtlIndicacionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Minsal\shcpBundle\Controller\ShcpParCtlIndicacionController();
        return $instance;
    }
}
